export const initialState = {
  tasks: [
    {
      id: 1,
      projectId: 1,
      numberTask: 1,
      title: "Задача",
      description: "Описание задачи 1.1",
      dateOfCreation: "2023-09-27",
      timeInWork: "2 часа",
      endDate: "2023-09-30",
      priority: "Средний",
      files: ["file1.docx", "file2.pdf"],
      status: "done",
      subtasks: [],
      comments: [],
      icon: "⭕️",
    },{
      id: 2,
      projectId: 1,
      numberTask: 21,
      title: "Задача",
      description: "Описание задачи 1.2",
      dateOfCreation: "2023-09-27",
      timeInWork: "2 часа",
      endDate: "2023-09-30",
      priority: "Средний",
      files: ["file1.docx", "file2.pdf"],
      status: "done",
      subtasks: [],
      comments: [],
      icon: "⭕️",
    },
    {
      id: 3,
      projectId: 23,
      numberTask: 1231,
      title: "Задача",
      description: "Описание задачи 2.1",
      dateOfCreation: "2023-09-27",
      timeInWork: "5 часа",
      endDate: "2023-09-30",
      priority: "Средний",
      files: ["file1.docx", "file23.pdf"],
      status: "development",
      subtasks: [],
      comments: [],
      icon: "⭕️",
    },
    {
      id: 4,
      projectId: 23,
      numberTask: 132,
      title: "Задача",
      description: "Описание задачи 2.2",
      dateOfCreation: "2023-09-27",
      timeInWork: "5 часа",
      endDate: "2023-09-30",
      priority: "Средний",
      files: ["file1.docx", "file23.pdf"],
      status: "development",
      subtasks: [],
      comments: [],
      icon: "⭕️",
    }
  ]
}